=== azizeoo/technomaker-xml-validation/target/classes/xml/descripteur.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="messages">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="message"/>
        <xs:element ref="informationsMessages"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="message">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="auteur"/>
        <xs:element ref="date"/>
        <xs:element ref="contenu"/>
      </xs:sequence>
      <xs:attribute name="reference" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="auteur" type="xs:NCName"/>
  <xs:element name="date" type="xs:NMTOKEN"/>
  <xs:element name="contenu" type="xs:string"/>
  <xs:element name="informationsMessages">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombreMessages"/>
        <xs:element ref="datePremierMessage"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombreMessages" type="xs:integer"/>
  <xs:element name="datePremierMessage" type="xs:NMTOKEN"/>
</xs:schema>

=== azizeoo/technomaker-xml-validation/src/main/resources/xml/donnees-messages.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="descripteur.xsd">

	<!-- Liste des messages -->
	<message reference="0">
		<auteur>Alice</auteur>
		<date>2011-06-07T11:53:45</date>
		<contenu>Bonjour tout le monde!!</contenu>
	</message>
	<message reference="1">
		<auteur nom="Guillaume"></auteur>
		<date>2011-06-07T11:54:12</date>
		<contenu>Hey salut! Comment vas tu ?</contenu>
	</message>
	<message>
		<auteur>Alice</auteur>
		<date>2011-06-07T11:54:58</date>
		<contenu>Super ;)</contenu>
	</message>
	<message reference="3">
		<auteur>Julien</auteur>
		<date>ce matin</date>
		<contenu>Bienvenue à tous! Vous connaissez le XML ?</contenu>
	</message>
	<message reference="4">
		<auteur>Guillaume</auteur>
		<contenu>Pas vraiment... :'(</contenu>
	</message>
	<message reference="5">
		<auteur>Alice</auteur>
		<date>2011-06-07T11:58:01</date>
		<contenu>Moi non plus, mais il parait que c'est très puissant!</contenu>
	</message>
	<message reference="6">
		<auteur>Julien</auteur>
		<date>2011-06-07T11:58:23</date>
		<contenu>Exact ;) En plus c'est utilisé dans de nombreuses applications</contenu>
	</message>
	<message reference="7">
		<Auteur>Alice</Auteur>
		<date>2011-06-07T11:58:49</date>
		<contenu>C'est souvent le cas quand le système est fiable</contenu>
	</message>
	<message reference="8">
		<auteur>Guillaume</auteur>
		<date>2011-06-07T11:59:21</date>
		<contenu>Allez Monsieur "JeSaisTout", dis nous tout! C'est quoi ce XML ? :)</contenu>
	</message>
	<message reference="9">
		<auteur>Julien</auteur>
		<mailAuteur>julien@mail.com</mailAuteur>
		<date>2011-06-07T11:59:46</date>
		<contenu>Héhé! Ok je commence! Il était une fois le XML...</contenu>
	</message>

	<!-- Informations diverses sur ces messages -->
	<informationsMessages>
		<nombreMessages>Dix</nombreMessages>
		<datePremierMessage>2011-06-07T11:53:45</datePremierMessage>
	</informationsMessages>

</messages>
